//
// Code auto-generated by initpackage (XSPEC12 local model package 
// code generator).  Do not edit
// Package: propfluc Created :
// Initializer: propfluc.cxx

#include <XSUser/UserInterface/xstcl.h>

#include  "propflucFunctionMap.h"
#include  <XSModelFunction.h>

extern "C" int Propfluc_Init(Tcl_Interp* tclInterp);
extern "C" int Propfluc_SafeInit(Tcl_Interp* tclInterp);

int Propfluc_Init(Tcl_Interp* tclInterp)
{
        return Propfluc_SafeInit(tclInterp);
}

int Propfluc_SafeInit(Tcl_Interp* tclInterp)
{

        char PACKAGE[] = "propfluc";
        char VERSION[] = "1.0";
        Tcl_PkgProvide(tclInterp, PACKAGE, VERSION);
        createpropflucFunctionMap();
        XSModelFunction::updateComponentList
              ("/home/itu/Dropbox/Zeta/Graduate_Thesis/ARMIN_SOFTWARE/Sinem/arminxspecv3/lmodel.dat");
        return TCL_OK;

}

