//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: propfluc
// Function header: propflucFunctionMap.h

#ifndef    FUNCTIONMAP_H
#define    FUNCTIONMAP_H

#include    <funcType.h>

class    XSModelFunction;

extern    ModelFunctionMap  XSFunctionMap;

void  createpropflucFunctionMap();

extern "C"  {


	xsf77Call    propfluc_;
}


#endif
