//
// Code auto-generated by initpackage (XSPEC12 local 
// model package code generator).  Do not edit.
// Package: propfluc
// Function body: propflucFunctionMap.cxx

#include    "propflucFunctionMap.h"

#include    <XSModelFunction.h>

void 
createpropflucFunctionMap()
{


	XSFunctionMap["propfluc"] = new XSCall<xsf77Call>(propfluc_);

}
